item {
    id: 1
    name: 'bin_empty'
}

item {
    id: 2
    name: 'image_badge'
}

item {
    id: 3
    name: 'image_bootlegger'
}

item {
    id: 4
    name: 'image_gman'
}

item {
    id: 5
    name: 'image_tommygun'
}

item {
    id: 6
    name: 'marker'
}

item {
    id: 7
    name: 'qual_gate'
}